# Generated by Django 4.2.7 on 2023-11-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_remove_item_discount_remove_item_tax_order_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='% скидки'),
        ),
    ]
